var menuData = [{
    name: 'menu.event',
    items: [{
        label: 'mvr.event',
        path: "/views/view_event",
        templateUrl: 'views/view_event.html',
    },{
        label: 'mvr.municipalities',
        path: "/views/view_municipalities",
        templateUrl: 'views/view_municipalities.html',
    }, {
        label: 'mvr.cities',
        path: "/views/view_cities",
        templateUrl: 'views/view_cities.html',
    }, {
        label: 'mvr.eventareas',
        path: "/views/view_eventareas",
        templateUrl: 'views/view_eventareas.html',
    }, {
        label: 'mvr.eventcommonareas',
        path: "/views/view_eventcommonareas",
        templateUrl: 'views/view_eventcommonareas.html',
    }, {
        label: 'mvr.eventcases',
        path: "/views/view_eventcases",
        templateUrl: 'views/view_eventcases.html',
    }, {
        label: 'mvr.eventcrimesagainstproperties',
        path: "/views/view_eventcrimesagainstproperties",
        templateUrl: 'views/view_eventcrimesagainstproperties.html',
    }, {
        label: 'mvr.eventmethodsofentering',
        path: "/views/view_eventmethodsofentering",
        templateUrl: 'views/view_eventmethodsofentering.html',
    }, {
        label: 'mvr.eventobjectsofattack',
        path: "/views/view_eventobjectsofattack",
        templateUrl: 'views/view_eventobjectsofattack.html',
    }, {
        label: 'mvr.eventpointsofentry',
        path: "/views/view_eventpointsofentry",
        templateUrl: 'views/view_eventpointsofentry.html',
    }, {
        label: 'mvr.eventpolicestations',
        path: "/views/view_eventpolicestations",
        templateUrl: 'views/view_eventpolicestations.html',
    }, {
        label: 'mvr.eventsuspectacts',
        path: "/views/view_eventsuspectacts",
        templateUrl: 'views/view_eventsuspectacts.html',
    }, {
        label: 'mvr.eventwayofleaving',
        path: "/views/view_eventwayofleaving",
        templateUrl: 'views/view_eventwayofleaving.html',
    }, {
        label: 'mvr.eventweapontypes',
        path: "/views/view_eventweapontypes",
        templateUrl: 'views/view_eventweapontypes.html',
    }, {
        label: 'mvr.personroles',
        path: "/views/view_personroles",
        templateUrl: 'views/view_personroles.html',
    }, {
        label: 'mvr.svrrc',
        path: "/views/view_svrrc",
        templateUrl: 'views/view_svrrc.html',
    }]
}, {
    name: 'menu.vehicle',
    items: [{
        label: 'mvr.vehicletype',
        path: "/views/view_vehicletype",
        templateUrl: 'views/view_vehicletypes.html',
    }, {
        label: 'mvr.vehiclecolor',
        path: "/views/view_vehiclecolor",
        templateUrl: 'views/view_vehiclecolor.html',
    }, {
        label: 'mvr.vehiclemodels',
        path: "/views/view_vehiclemodels",
        templateUrl: 'views/view_vehiclemodels.html',
    }, {
        label: 'mvr.vehiclebrends',
        path: "/views/view_vehiclebrends",
        templateUrl: 'views/view_vehiclebrends.html',
    }, {
        label: 'mvr.vehicleregcountries',
        path: "/views/view_vehicleregcountries",
        templateUrl: 'views/view_vehicleregcountries.html',
    }, {
        label: 'mvr.vehicles',
        path: "/views/view_vehicles",
        templateUrl: 'views/view_vehicles.html',
    }, {
        label: 'mvr.vehiclesofpersons',
        path: "/views/view_vehiclesofpersons",
        templateUrl: 'views/view_vehiclesofpersons.html',
    },{
        label: 'mvr.vehiclesinevents',
        path: "/views/view_vehiclesinevents",
        templateUrl: 'views/view_vehiclesinevents.html',
    }]

}, {
    name: 'menu.article',
    items: [{
        label: 'mvr.articletypes',
        path: "/views/view_articletypes",
        templateUrl: 'views/view_articletypes.html',
    }, {
        label: 'mvr.articleunits',
        path: "/views/view_articleunits",
        templateUrl: 'views/view_articleunits.html',
    }, {
        label: 'mvr.articles',
        path: "/views/view_articles",
        templateUrl: 'views/view_articles.html',
    }, {
        label: 'mvr.articlesinevents',
        path: "/views/view_articlesinevents",
        templateUrl: 'views/view_articlesinevents.html',
    }
    ] 
}, {
    name: 'menu.person',
    items: [{
        label: 'mvr.ethnicity',
        path: "/views/view_ethnicity",
        templateUrl: 'views/view_ethnicity.html',
    }, {
        label: 'mvr.age',
        path: "/views/view_age",
        templateUrl: 'views/view_age.html',
    }, {
        label: 'mvr.skintypes',
        path: "/views/view_skintypes",
        templateUrl: 'views/view_skintypes.html',
    }, {
        label: 'mvr.heights',
        path: "/views/view_heights",
        templateUrl: 'views/view_heights.html',
    }, {
        label: 'mvr.weights',
        path: "/views/view_weights",
        templateUrl: 'views/view_weights.html',
    }, {
        label: 'mvr.teethconditions',
        path: "/views/view_teethconditions",
        templateUrl: 'views/view_teethconditions.html',
    }, {
        label: 'mvr.speachtroubles',
        path: "/views/view_speachtroubles",
        templateUrl: 'views/view_speachtroubles.html',
    }, {
        label: 'mvr.physicalconditions',
        path: "/views/view_physicalconditions",
        templateUrl: 'views/view_physicalconditions.html',
    }, {
        label: 'mvr.humancharacteristics',
        path: "/views/view_humancharacteristics",
        templateUrl: 'views/view_humancharacteristics.html',
    }, {
        label: 'mvr.handtypes',
        path: "/views/view_handtypes",
        templateUrl: 'views/view_handtypes.html',
    }, {
        label: 'mvr.haircolors',
        path: "/views/view_haircolors",
        templateUrl: 'views/view_haircolors.html',
    }, {
        label: 'mvr.facialhairtypes',
        path: "/views/view_facialhairtypes",
        templateUrl: 'views/view_facialhairtypes.html',
    }, {
        label: 'mvr.eyecolors',
        path: "/views/view_eyecolors",
        templateUrl: 'views/view_eyecolors.html',
    }, {
        label: 'mvr.bodytypes',
        path: "/views/view_bodytypes",
        templateUrl: 'views/view_bodytypes.html',
    }, {
        label: 'mvr.nationalities',
        path: "/views/view_nationalities",
        templateUrl: 'views/view_nationalities.html',
    }, {
        label: 'mvr.specifiedpersons',
        path: "/views/view_specifiedpersons",
        templateUrl: 'views/view_specifiedpersons.html',
        controller: 'specifiedPersonController'
    }, {
        label: 'mvr.unspecifiedpersons',
        path: "/views/view_unspecifiedpersons",
        templateUrl: 'views/view_unspecifiedpersons.html',
    }, {
        label: 'mvr.specifiedpersonsinevents',
        path: "/views/view_specifiedpersonsinevents",
        templateUrl: 'views/view_specifiedpersonsinevents.html',
    }, {
        label: 'mvr.unspecifiedpersonsinevents',
        path: "/views/view_unspecifiedpersonsinevents",
        templateUrl: 'views/view_unspecifiedpersonsinevents.html',
    }]  
}];